version: '3'
services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile
      # network: host
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
      - /opt/app/.next
    ports:
      - '3000:3000'