FROM node:16.13-alpine

RUN mkdir -p /opt/app
EXPOSE 3000
WORKDIR /opt/app

ENV PORT=3000
ENV HOST=0.0.0.0
ENV NODE_ENV=production

COPY package.json /opt/app
COPY yarn.lock /opt/app
COPY .eslintrc.json /opt/app/.eslintrc.json
COPY package.json *.lock ./
COPY prisma ./prisma/ 
RUN yarn install --production
RUN yarn add --dev eslint
COPY . /opt/app

RUN yarn build
CMD [ "yarn", "start" ]
