on:
  push:
    branches:
      - main
name: 🚀 Deploy Production
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v1
      - name: Deploy Production server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "./menuOnline-backend/"
          SCRIPT_AFTER: |         
            #!/bin/bash    
            cd menuOnline-backend
            echo "${{ vars.VAR_BUILD }}" | sed 's/ \+/\n/g' > .env;
            
            docker rm -vf nextjs
            docker rmi -f $(docker images -q | grep -v nextjs)
      
            docker rm -vf mysql
            docker rmi -f $(docker images -q | grep -v mysql)
      
            docker rm -vf minio
            docker rmi -f $(docker images -q | grep -v minio)

            make build;